language: c

cache:
  directories:
    - $HOME/.cabal
    - $HOME/.ghc

env: CABALVER=1.22 GHCVER=7.10.3
addons: {apt: {packages: [cabal-install-1.22, ghc-7.10.3], sources: [hvr-ghc]}}

install:
  - export PATH=$HOME/.local/bin:/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$PATH
  - cabal update
  - cabal install happy

script:
  - cabal install ./
